### ISSUE TITLE
Unable to add the Package

### ISSUE THREAD

**Issue by kirshanthans** [thomasfaingnaert/GemmKernels.jl#48]
When I try to add the package, I get the following error message.
(@v1.5) pkg> add https://github.com/thomasfaingnaert/GemmKernels.jl
   Updating git-repo `https://github.com/thomasfaingnaert/GemmKernels.jl`
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CUDA [052768ef]:
 CUDA [052768ef] log:
 ├─possible versions are: [0.1.0, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0-1.3.3] or uninstalled
 ├─restricted to versions 1.3.0-1 by GemmKernels [312cec97], leaving only versions 1.3.0-1.3.3
 │ └─GemmKernels [312cec97] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─GemmKernels [312cec97] is fixed to version 0.1.0
 └─restricted by compatibility requirements with LLVM [929cbde3] to versions: uninstalled — no versions left
   └─LLVM [929cbde3] log:
     ├─possible versions are: [0.9.0-0.9.15, 1.0.0, 1.1.0-1.1.1, 1.2.0, 1.3.0-1.3.4, 1.4.0-1.4.1, 1.5.0-1.5.2, 1.6.0, 1.7.0, 2.0.0, 3.0.0, 3.1.0] or uninstalled
     └─restricted to versions 3 by GemmKernels [312cec97], leaving only versions [3.0.0, 3.1.0]
       └─GemmKernels [312cec97] log: see above

**Comment by thomasfaingnaert** [comment]
Could you try again with an empty environment?Op 1 okt. 2020 17:54 schreef Kirshanthan Sundararajah <notifications@github.com>:

(@v1.5) pkg> add https://github.com/thomasfaingnaert/GemmKernels.jl

Updating git-repo https://github.com/thomasfaingnaert/GemmKernels.jl

Resolving package versions...

ERROR: Unsatisfiable requirements detected for package CUDA [052768ef]:

CUDA [052768ef] log:

├─possible versions are: [0.1.0, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0-1.3.3] or uninstalled

├─restricted to versions 1.3.0-1 by GemmKernels [312cec97], leaving only versions 1.3.0-1.3.3

│ └─GemmKernels [312cec97] log:

│   ├─possible versions are: 0.1.0 or uninstalled

│   └─GemmKernels [312cec97] is fixed to version 0.1.0

└─restricted by compatibility requirements with LLVM [929cbde3] to versions: uninstalled — no versions left

└─LLVM [929cbde3] log:

├─possible versions are: [0.9.0-0.9.15, 1.0.0, 1.1.0-1.1.1, 1.2.0, 1.3.0-1.3.4, 1.4.0-1.4.1, 1.5.0-1.5.2, 1.6.0, 1.7.0, 2.0.0, 3.0.0, 3.1.0] or uninstalled

└─restricted to versions 3 by GemmKernels [312cec97], leaving only versions [3.0.0, 3.1.0]

└─GemmKernels [312cec97] log: see above

**Comment by kirshanthans** [comment]
Great, It works now. Thank you.
